name: element_ubuntu
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=1.1.1l
  - pip=20.0.2
  - python=3.7.2
  - python_abi=3.7
  - readline=7.0
  - setuptools=58.2.0
  - sqlite=3.28.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.15.0
    - astor==0.8.1
    - cached-property==1.5.2
    - cffi==1.15.0
    - cycler==0.10.0
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.41.0
    - h5py==3.5.0
    - imageio==2.9.0
    - imgaug==0.4.0
    - importlib-metadata==4.8.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - markdown==3.3.4
    - matplotlib==3.4.3
    - networkx==2.6.3
    - numpy==1.21.2
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - pandas==1.3.3
    - patsy==0.5.2
    - pillow==7.0.0
    - plotly==5.3.1
    - plotly-express==0.4.1
    - portalocker==1.5.2
    - protobuf==3.18.1
    - pycparser==2.20
    - pycrypto==2.6.1
    - pynng==0.4.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - scikit-image==0.18.3
    - scipy==1.7.1
    - shapely==1.7.1
    - six==1.16.0
    - sniffio==1.2.0
    - sqlalchemy==1.3.19
    - statsmodels==0.13.0
    - tenacity==8.0.1
    - tensorboard==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.0
    - termcolor==1.1.0
    - tifffile==2021.10.10
    - typing-extensions==3.10.0.2
    - utm==0.7.0
    - werkzeug==2.0.2
    - wrapt==1.13.1
    - zipp==3.6.0

