name: element_windows
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.9.30
  - geos=3.9.1
  - openssl=1.1.1l
  - pip=20.0.2
  - python=3.7.2
  - python_abi=3.7
  - setuptools=58.2.0
  - sqlite=3.36.0
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.37.0
  - pip:
    - absl-py==0.14.1
    - astor==0.8.1
    - cached-property==1.5.2
    - cffi==1.14.6
    - click==8.0.3
    - colorama==0.4.4
    - cycler==0.10.0
    - flask==2.0.2
    - gast==0.2.2
    - google-pasta==0.2.0
    - grpcio==1.41.0
    - h5py==3.4.0
    - imageio==2.8.0
    - imgaug==0.4.0
    - importlib-metadata==4.8.1
    - itsdangerous==2.0.1
    - jinja2==3.0.2
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.2
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - networkx==2.6.3
    - numpy==1.21.2
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - pandas==1.3.3
    - patsy==0.5.2
    - pillow==7.0.0
    - plotly==5.3.1
    - plotly-express==0.4.1
    - portalocker==1.5.2
    - protobuf==3.18.1
    - psycopg2==2.8.5
    - pycparser==2.20
    - pycryptodome==3.11.0
    - pynng==0.4.0
    - pyparsing==3.0.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - pywin32==301
    - scikit-image==0.18.3
    - scipy==1.7.1
    - seaborn==0.11.2
    - shapely==1.8.0
    - six==1.16.0
    - sniffio==1.2.0
    - sqlalchemy==1.3.19
    - statsmodels==0.13.0
    - tenacity==8.0.1
    - tensorflow-gpu==2.6.0
    - termcolor==1.1.0
    - tifffile==2021.10.10
    - typing-extensions==3.10.0.2
    - utm==0.7.0
    - werkzeug==2.0.2
    - wrapt==1.13.1
    - zipp==3.6.0
